//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFavouriteMovy
    {
        public int UFavMovieId { get; set; }
        public int UserId { get; set; }
        public string Fav1 { get; set; }
        public string Fav2 { get; set; }
        public string Fav3 { get; set; }
        public string Fav4 { get; set; }
    
        public virtual User User { get; set; }
    }
}
