USE [master]
GO
/****** Object:  Database [DemoDb]    Script Date: 24-03-2020 18:43:22 ******/
CREATE DATABASE [DemoDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DemoDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\DemoDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DemoDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\DemoDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [DemoDb] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DemoDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DemoDb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DemoDb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DemoDb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DemoDb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DemoDb] SET ARITHABORT OFF 
GO
ALTER DATABASE [DemoDb] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DemoDb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DemoDb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DemoDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DemoDb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DemoDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DemoDb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DemoDb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DemoDb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DemoDb] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DemoDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DemoDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DemoDb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DemoDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DemoDb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DemoDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DemoDb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DemoDb] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DemoDb] SET  MULTI_USER 
GO
ALTER DATABASE [DemoDb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DemoDb] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DemoDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DemoDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [DemoDb] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [DemoDb] SET QUERY_STORE = OFF
GO
USE [DemoDb]
GO
/****** Object:  Table [dbo].[Actors]    Script Date: 24-03-2020 18:43:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Actors](
	[ActorId] [int] IDENTITY(1,1) NOT NULL,
	[ActorName] [varchar](30) NOT NULL,
 CONSTRAINT [PK_Actors] PRIMARY KEY CLUSTERED 
(
	[ActorId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MovieDetails]    Script Date: 24-03-2020 18:43:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MovieDetails](
	[MovieDetailId] [int] IDENTITY(1,1) NOT NULL,
	[MovieId] [int] NOT NULL,
	[ActorId] [int] NOT NULL,
 CONSTRAINT [PK_MovieDetails] PRIMARY KEY CLUSTERED 
(
	[MovieDetailId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Movies]    Script Date: 24-03-2020 18:43:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Movies](
	[MovieId] [int] IDENTITY(1,1) NOT NULL,
	[MovieName] [varchar](30) NOT NULL,
 CONSTRAINT [PK_Movies] PRIMARY KEY CLUSTERED 
(
	[MovieId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserFavouriteMovies]    Script Date: 24-03-2020 18:43:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserFavouriteMovies](
	[UFavMovieId] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [int] NOT NULL,
	[Fav1] [varchar](30) NOT NULL,
	[Fav2] [varchar](30) NOT NULL,
	[Fav3] [varchar](30) NOT NULL,
	[Fav4] [varchar](30) NOT NULL,
 CONSTRAINT [PK_UserFavouriteMovies] PRIMARY KEY CLUSTERED 
(
	[UFavMovieId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 24-03-2020 18:43:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[UserId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](20) NOT NULL,
	[Gender] [varchar](10) NOT NULL,
	[ContactNo] [bigint] NOT NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MovieDetails]  WITH CHECK ADD  CONSTRAINT [FK_MovieDetails_Actors] FOREIGN KEY([ActorId])
REFERENCES [dbo].[Actors] ([ActorId])
GO
ALTER TABLE [dbo].[MovieDetails] CHECK CONSTRAINT [FK_MovieDetails_Actors]
GO
ALTER TABLE [dbo].[MovieDetails]  WITH CHECK ADD  CONSTRAINT [FK_MovieDetails_Movies] FOREIGN KEY([MovieId])
REFERENCES [dbo].[Movies] ([MovieId])
GO
ALTER TABLE [dbo].[MovieDetails] CHECK CONSTRAINT [FK_MovieDetails_Movies]
GO
ALTER TABLE [dbo].[UserFavouriteMovies]  WITH CHECK ADD  CONSTRAINT [FK_UserFavouriteMovies_Users] FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([UserId])
GO
ALTER TABLE [dbo].[UserFavouriteMovies] CHECK CONSTRAINT [FK_UserFavouriteMovies_Users]
GO
USE [master]
GO
ALTER DATABASE [DemoDb] SET  READ_WRITE 
GO
